name: MLOps Churn Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "src/training/**"
      - "data/**"
      - "pipelines/azure_train_job.yml"
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_ct]

jobs:
  train-and-deploy:
    name: Train and Deploy Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Azure ML CLI
        run: |
          pip install azure-ai-ml
          az extension add -n ml -y

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure ML workspace defaults
        run: |
          az configure --defaults group=${{ secrets.AZURE_RESOURCE_GROUP }} workspace=${{ secrets.AZURE_ML_WORKSPACE }}

      - name: Materialize Feast Features to Redis
        env:
          REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
        run: |
          pip install pandas pyarrow "feast[redis]" numpy "dvc[azure]"
          # Lấy Connection String động từ Azure CLI đã login
          CONN_STR=$(az storage account show-connection-string --name churnmlopsws2289572105 --resource-group mlops-churn-rg --query connectionString -o tsv)
          dvc remote modify --local myremote connection_string "$CONN_STR"
          dvc pull
          python src/training/materialize.py

      - name: Submit Training Job
        id: training
        run: |
          JOB_NAME=$(az ml job create -f pipelines/azure_train_job.yml --query name -o tsv)
          echo "job_name=$JOB_NAME" >> $GITHUB_OUTPUT
          echo "Training job submitted: $JOB_NAME"

      - name: Wait for Training Job to complete
        run: |
          echo "Waiting for job: ${{ steps.training.outputs.job_name }}"
          for i in $(seq 1 40); do
            STATUS=$(az ml job show --name ${{ steps.training.outputs.job_name }} --query status -o tsv)
            echo "Attempt $i - Status: $STATUS"
            if [ "$STATUS" = "Completed" ]; then
              echo "Training job completed successfully."
              break
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Canceled" ]; then
              echo "Training job failed with status: $STATUS"
              exit 1
            fi
            sleep 60
          done

      - name: Update Deployment with new model
        run: |
          az ml online-deployment update \
            --name blue \
            --endpoint-name churn-endpoint \
            -f pipelines/azure_deployment.yml
